In [9]:
import numpy as np 
np.random.rand(2)

array([0.74155451, 0.56000712])

In [7]:
np.random.rand(2,4)

array([[0.85862657, 0.74352231, 0.7404068 , 0.52055212],
       [0.19648031, 0.87147615, 0.45305303, 0.47077913]])

In [9]:
np.random.rand(2,4,3)

array([[[0.61452833, 0.72541559, 0.77680747],
        [0.44248457, 0.97049642, 0.34580293],
        [0.05890152, 0.89836408, 0.41767494],
        [0.21138027, 0.97455914, 0.21231505]],

       [[0.13604136, 0.69854609, 0.87432493],
        [0.63757769, 0.56521267, 0.44044857],
        [0.57603641, 0.434643  , 0.60918156],
        [0.30766536, 0.83366148, 0.38015017]]])

In [13]:
np.random.randint(2)

0

In [17]:
np.random.randint(2,5)

4

In [22]:
np.random.randint(2,5,8)

array([3, 3, 2, 4, 3, 3, 3, 4])

In [24]:
np.random.randint(2,5,(2,3))

array([[3, 2, 2],
       [2, 2, 4]])

In [26]:
np.arange(1,3)

array([1, 2])

In [28]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [30]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [44]:
b = np.random.randint(3,7,3)

In [46]:
b

array([5, 6, 6])

In [48]:
type(b)

numpy.ndarray

In [50]:
b= np.random.randint(10,20,(3,4))

In [52]:
b

array([[11, 16, 10, 17],
       [12, 12, 10, 19],
       [14, 16, 17, 16]])

In [54]:
b[:]

array([[11, 16, 10, 17],
       [12, 12, 10, 19],
       [14, 16, 17, 16]])

In [56]:
b[1:3]

array([[12, 12, 10, 19],
       [14, 16, 17, 16]])

In [58]:
b[:3]

array([[11, 16, 10, 17],
       [12, 12, 10, 19],
       [14, 16, 17, 16]])

In [60]:
b[1:]

array([[12, 12, 10, 19],
       [14, 16, 17, 16]])

In [62]:
b[1,2]

10

In [64]:
b[1,1]

12

In [66]:
b[1:5]

array([[12, 12, 10, 19],
       [14, 16, 17, 16]])

In [68]:
b[2,3]

16

In [78]:
b[-1,-2]

17

In [80]:
b

array([[11, 16, 10, 17],
       [12, 12, 10, 19],
       [14, 16, 17, 16]])

In [86]:
b[0:-2]

array([[11, 16, 10, 17]])

In [88]:
b[0:-1]

array([[11, 16, 10, 17],
       [12, 12, 10, 19]])

In [92]:
b[0:2]

array([[11, 16, 10, 17],
       [12, 12, 10, 19]])

In [94]:
b[1:3]

array([[12, 12, 10, 19],
       [14, 16, 17, 16]])

In [96]:
b[2,3]

16

In [11]:
arr = np.random.randint(10,20,(5,5))

In [110]:
arr

array([[10, 14, 14, 14, 15],
       [11, 15, 13, 10, 14],
       [15, 15, 16, 12, 14],
       [11, 12, 14, 11, 13],
       [13, 15, 13, 13, 14]])

In [108]:
arr[1:2]

array([[11, 15, 13, 10, 14]])

In [112]:
arr[1:-3]

array([[11, 15, 13, 10, 14]])

In [114]:
arr[2:-3]

array([], shape=(0, 5), dtype=int32)

In [116]:
arr[1,2]

13

In [118]:
arr[:-1]

array([[10, 14, 14, 14, 15],
       [11, 15, 13, 10, 14],
       [15, 15, 16, 12, 14],
       [11, 12, 14, 11, 13]])

In [120]:
arr[::-1]

array([[13, 15, 13, 13, 14],
       [11, 12, 14, 11, 13],
       [15, 15, 16, 12, 14],
       [11, 15, 13, 10, 14],
       [10, 14, 14, 14, 15]])

In [15]:
arr

array([[13, 16, 14, 18, 14],
       [19, 11, 19, 12, 18],
       [19, 10, 11, 12, 15],
       [10, 15, 17, 14, 17],
       [16, 13, 19, 13, 11]])

In [21]:
arr[::-2]

array([[16, 13, 19, 13, 11],
       [19, 10, 11, 12, 15],
       [13, 16, 14, 18, 14]])

In [23]:
arr[::-3]

array([[16, 13, 19, 13, 11],
       [19, 11, 19, 12, 18]])

In [25]:
arr[::-4]

array([[16, 13, 19, 13, 11],
       [13, 16, 14, 18, 14]])

In [27]:
arr[::1]

array([[13, 16, 14, 18, 14],
       [19, 11, 19, 12, 18],
       [19, 10, 11, 12, 15],
       [10, 15, 17, 14, 17],
       [16, 13, 19, 13, 11]])

In [29]:
arr[::2]

array([[13, 16, 14, 18, 14],
       [19, 10, 11, 12, 15],
       [16, 13, 19, 13, 11]])

In [33]:
arr.max()

19

In [36]:
arr.min()

10

In [38]:
arr.mean()

14.64

In [44]:
import numpy as np
np.median(arr)

14.0

In [46]:
from numpy import * 
median(arr)

14.0

In [48]:
median(arr)

14.0

In [50]:
np.arange(2,5)

array([2, 3, 4])

In [78]:
arr=np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr.reshape(4,2)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [90]:
arr.reshape(4,2,order='C')

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [84]:
arr.reshape(4,2,order='F')

array([[2, 6],
       [3, 7],
       [4, 8],
       [5, 9]])

In [86]:
arr.reshape(4,2,order='A')

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [96]:
arr1 = arange(0,6)

In [98]:
arr1

array([0, 1, 2, 3, 4, 5])

In [102]:
arr1.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [104]:
arr1.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [110]:
arr1.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [112]:
arr1.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [114]:
arr1.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [116]:
arr1.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [118]:
arr1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [120]:
arr1.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [147]:
mat= arange(0,100)

In [128]:
mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [189]:
mat.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [191]:
mat.reshape(10,10,order='A')

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [193]:
row = 4
col= 5

In [195]:
mat[row:col]

array([4])

In [175]:
mat[4:5]

array([4])

In [179]:
mat[6]

6

In [197]:
mat[row,col]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [201]:
mat[:,6]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
mat[:,5]

In [230]:
m = arange(0,100)

In [309]:
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [311]:
m.reshape(10,10,order='C')

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [325]:
row = 3
col=4
m[row:col,row:col]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [321]:
m[row,:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [252]:
m[2:6,2:4]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [250]:
id(m)

2626804063120

In [254]:
m < 50

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [258]:
m[m<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [260]:
m[m>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [262]:
mat > 50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [272]:
a= np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [282]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [305]:
row=1
col=2
a[row:col]

array([1])